/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CallId = IDL.Nat;
export const GroupId = IDL.Nat;
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateGroupRequest = IDL.Record({
  'icon' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const EditGroupRequest = IDL.Record({
  'icon' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PresenceStatus = IDL.Variant({
  'away' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ProfilePublic = IDL.Record({
  'status' : IDL.Text,
  'username' : IDL.Text,
  'userId' : UserId,
  'presence' : PresenceStatus,
  'lastSeen' : Timestamp,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const CallStatus = IDL.Variant({
  'active' : IDL.Null,
  'ringing' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallStatePublic = IDL.Record({
  'id' : CallId,
  'status' : CallStatus,
  'callerCandidates' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'sdpOffer' : IDL.Opt(IDL.Text),
  'calleeId' : UserId,
  'callerId' : UserId,
  'updatedAt' : Timestamp,
  'calleeCandidates' : IDL.Vec(IDL.Text),
  'isVideo' : IDL.Bool,
  'sdpAnswer' : IDL.Opt(IDL.Text),
});
export const Contact = IDL.Record({
  'username' : IDL.Text,
  'userId' : UserId,
  'addedAt' : Timestamp,
});
export const MessageId = IDL.Nat;
export const MessageKind = IDL.Variant({
  'file' : IDL.Null,
  'text' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'kind' : MessageKind,
  'createdAt' : Timestamp,
  'senderId' : UserId,
});
export const DirectConversationSummary = IDL.Record({
  'otherUsername' : IDL.Text,
  'otherUserId' : UserId,
  'lastMessage' : IDL.Opt(Message),
  'conversationId' : IDL.Nat,
  'unreadCount' : IDL.Nat,
});
export const Group = IDL.Record({
  'id' : GroupId,
  'ownerId' : UserId,
  'icon' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const GroupMemberRole = IDL.Variant({
  'member' : IDL.Null,
  'owner' : IDL.Null,
});
export const GroupMember = IDL.Record({
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : GroupMemberRole,
  'groupId' : GroupId,
});
export const ContactStatus = IDL.Variant({
  'pending' : IDL.Null,
  'blocked' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ContactRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : UserId,
  'status' : ContactStatus,
  'from' : UserId,
  'createdAt' : Timestamp,
});
export const ReactionEntry = IDL.Record({
  'emoji' : IDL.Text,
  'users' : IDL.Vec(UserId),
});
export const GroupSummary = IDL.Record({
  'memberCount' : IDL.Nat,
  'lastMessage' : IDL.Opt(MessageId),
  'group' : Group,
  'unreadCount' : IDL.Nat,
});
export const SaveProfileRequest = IDL.Record({
  'status' : IDL.Text,
  'username' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const ConversationType = IDL.Variant({
  'group' : IDL.Null,
  'direct' : IDL.Null,
});
export const SearchResult = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Nat,
  'createdAt' : Timestamp,
  'conversationId' : IDL.Text,
  'senderId' : UserId,
  'conversationType' : ConversationType,
});
export const SendMessageRequest = IDL.Record({
  'content' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptCall' : IDL.Func([CallId, IDL.Text], [], []),
  'acceptContactRequest' : IDL.Func([IDL.Nat], [], []),
  'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'addIceCandidate' : IDL.Func([CallId, IDL.Text, IDL.Bool], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCall' : IDL.Func([UserId, IDL.Text, IDL.Bool], [CallId], []),
  'createGroup' : IDL.Func([CreateGroupRequest], [GroupId], []),
  'declineCall' : IDL.Func([CallId], [], []),
  'editGroup' : IDL.Func([GroupId, EditGroupRequest], [], []),
  'findUserByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProfilePublic)],
      ['query'],
    ),
  'getCallState' : IDL.Func([CallId], [IDL.Opt(CallStatePublic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getDirectConversationSummaries' : IDL.Func(
      [],
      [IDL.Vec(DirectConversationSummary)],
      ['query'],
    ),
  'getDirectMessageReaders' : IDL.Func(
      [IDL.Nat, MessageId],
      [IDL.Vec(UserId)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [IDL.Nat, IDL.Opt(MessageId), IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupMembers' : IDL.Func([GroupId], [IDL.Vec(GroupMember)], ['query']),
  'getGroupMessageReaders' : IDL.Func(
      [GroupId, MessageId],
      [IDL.Vec(UserId)],
      ['query'],
    ),
  'getGroupMessages' : IDL.Func(
      [GroupId, IDL.Opt(MessageId), IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOrCreateDirectConversation' : IDL.Func([UserId], [IDL.Nat], []),
  'getPendingCall' : IDL.Func([], [IDL.Opt(CallStatePublic)], ['query']),
  'getPendingContactRequests' : IDL.Func(
      [],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getReactions' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ReactionEntry)],
      ['query'],
    ),
  'getSentContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getTypingUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserId)], ['query']),
  'getUnreadDirectCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserGroups' : IDL.Func([], [IDL.Vec(GroupSummary)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfilePublic)], ['query']),
  'hangupCall' : IDL.Func([CallId], [], []),
  'heartbeat' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveGroup' : IDL.Func([GroupId], [], []),
  'markDirectRead' : IDL.Func([IDL.Nat, MessageId], [], []),
  'markGroupRead' : IDL.Func([GroupId, MessageId], [], []),
  'rejectContactRequest' : IDL.Func([IDL.Nat], [], []),
  'removeContact' : IDL.Func([UserId], [], []),
  'removeGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'removeReaction' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileRequest], [], []),
  'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendContactRequest' : IDL.Func([UserId], [IDL.Nat], []),
  'sendDirectMessage' : IDL.Func(
      [IDL.Nat, SendMessageRequest],
      [MessageId],
      [],
    ),
  'sendGroupMessage' : IDL.Func([GroupId, SendMessageRequest], [MessageId], []),
  'setPresence' : IDL.Func([PresenceStatus], [], []),
  'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CallId = IDL.Nat;
  const GroupId = IDL.Nat;
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateGroupRequest = IDL.Record({
    'icon' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const EditGroupRequest = IDL.Record({
    'icon' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PresenceStatus = IDL.Variant({
    'away' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ProfilePublic = IDL.Record({
    'status' : IDL.Text,
    'username' : IDL.Text,
    'userId' : UserId,
    'presence' : PresenceStatus,
    'lastSeen' : Timestamp,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const CallStatus = IDL.Variant({
    'active' : IDL.Null,
    'ringing' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallStatePublic = IDL.Record({
    'id' : CallId,
    'status' : CallStatus,
    'callerCandidates' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'sdpOffer' : IDL.Opt(IDL.Text),
    'calleeId' : UserId,
    'callerId' : UserId,
    'updatedAt' : Timestamp,
    'calleeCandidates' : IDL.Vec(IDL.Text),
    'isVideo' : IDL.Bool,
    'sdpAnswer' : IDL.Opt(IDL.Text),
  });
  const Contact = IDL.Record({
    'username' : IDL.Text,
    'userId' : UserId,
    'addedAt' : Timestamp,
  });
  const MessageId = IDL.Nat;
  const MessageKind = IDL.Variant({ 'file' : IDL.Null, 'text' : IDL.Null });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'kind' : MessageKind,
    'createdAt' : Timestamp,
    'senderId' : UserId,
  });
  const DirectConversationSummary = IDL.Record({
    'otherUsername' : IDL.Text,
    'otherUserId' : UserId,
    'lastMessage' : IDL.Opt(Message),
    'conversationId' : IDL.Nat,
    'unreadCount' : IDL.Nat,
  });
  const Group = IDL.Record({
    'id' : GroupId,
    'ownerId' : UserId,
    'icon' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const GroupMemberRole = IDL.Variant({
    'member' : IDL.Null,
    'owner' : IDL.Null,
  });
  const GroupMember = IDL.Record({
    'userId' : UserId,
    'joinedAt' : Timestamp,
    'role' : GroupMemberRole,
    'groupId' : GroupId,
  });
  const ContactStatus = IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ContactRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : UserId,
    'status' : ContactStatus,
    'from' : UserId,
    'createdAt' : Timestamp,
  });
  const ReactionEntry = IDL.Record({
    'emoji' : IDL.Text,
    'users' : IDL.Vec(UserId),
  });
  const GroupSummary = IDL.Record({
    'memberCount' : IDL.Nat,
    'lastMessage' : IDL.Opt(MessageId),
    'group' : Group,
    'unreadCount' : IDL.Nat,
  });
  const SaveProfileRequest = IDL.Record({
    'status' : IDL.Text,
    'username' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const ConversationType = IDL.Variant({
    'group' : IDL.Null,
    'direct' : IDL.Null,
  });
  const SearchResult = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Nat,
    'createdAt' : Timestamp,
    'conversationId' : IDL.Text,
    'senderId' : UserId,
    'conversationType' : ConversationType,
  });
  const SendMessageRequest = IDL.Record({
    'content' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptCall' : IDL.Func([CallId, IDL.Text], [], []),
    'acceptContactRequest' : IDL.Func([IDL.Nat], [], []),
    'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'addIceCandidate' : IDL.Func([CallId, IDL.Text, IDL.Bool], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCall' : IDL.Func([UserId, IDL.Text, IDL.Bool], [CallId], []),
    'createGroup' : IDL.Func([CreateGroupRequest], [GroupId], []),
    'declineCall' : IDL.Func([CallId], [], []),
    'editGroup' : IDL.Func([GroupId, EditGroupRequest], [], []),
    'findUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProfilePublic)],
        ['query'],
      ),
    'getCallState' : IDL.Func([CallId], [IDL.Opt(CallStatePublic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getDirectConversationSummaries' : IDL.Func(
        [],
        [IDL.Vec(DirectConversationSummary)],
        ['query'],
      ),
    'getDirectMessageReaders' : IDL.Func(
        [IDL.Nat, MessageId],
        [IDL.Vec(UserId)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [IDL.Nat, IDL.Opt(MessageId), IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupMembers' : IDL.Func([GroupId], [IDL.Vec(GroupMember)], ['query']),
    'getGroupMessageReaders' : IDL.Func(
        [GroupId, MessageId],
        [IDL.Vec(UserId)],
        ['query'],
      ),
    'getGroupMessages' : IDL.Func(
        [GroupId, IDL.Opt(MessageId), IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOrCreateDirectConversation' : IDL.Func([UserId], [IDL.Nat], []),
    'getPendingCall' : IDL.Func([], [IDL.Opt(CallStatePublic)], ['query']),
    'getPendingContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getReactions' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ReactionEntry)],
        ['query'],
      ),
    'getSentContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getTypingUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserId)], ['query']),
    'getUnreadDirectCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserGroups' : IDL.Func([], [IDL.Vec(GroupSummary)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(ProfilePublic)], ['query']),
    'hangupCall' : IDL.Func([CallId], [], []),
    'heartbeat' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveGroup' : IDL.Func([GroupId], [], []),
    'markDirectRead' : IDL.Func([IDL.Nat, MessageId], [], []),
    'markGroupRead' : IDL.Func([GroupId, MessageId], [], []),
    'rejectContactRequest' : IDL.Func([IDL.Nat], [], []),
    'removeContact' : IDL.Func([UserId], [], []),
    'removeGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'removeReaction' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileRequest], [], []),
    'searchMessages' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendContactRequest' : IDL.Func([UserId], [IDL.Nat], []),
    'sendDirectMessage' : IDL.Func(
        [IDL.Nat, SendMessageRequest],
        [MessageId],
        [],
      ),
    'sendGroupMessage' : IDL.Func(
        [GroupId, SendMessageRequest],
        [MessageId],
        [],
      ),
    'setPresence' : IDL.Func([PresenceStatus], [], []),
    'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };