/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CallId = bigint;
export interface CallStatePublic {
  'id' : CallId,
  'status' : CallStatus,
  'callerCandidates' : Array<string>,
  'createdAt' : Timestamp,
  'sdpOffer' : [] | [string],
  'calleeId' : UserId,
  'callerId' : UserId,
  'updatedAt' : Timestamp,
  'calleeCandidates' : Array<string>,
  'isVideo' : boolean,
  'sdpAnswer' : [] | [string],
}
export type CallStatus = { 'active' : null } |
  { 'ringing' : null } |
  { 'missed' : null } |
  { 'ended' : null } |
  { 'declined' : null };
export interface Contact {
  'username' : string,
  'userId' : UserId,
  'addedAt' : Timestamp,
}
export interface ContactRequest {
  'id' : bigint,
  'to' : UserId,
  'status' : ContactStatus,
  'from' : UserId,
  'createdAt' : Timestamp,
}
export type ContactStatus = { 'pending' : null } |
  { 'blocked' : null } |
  { 'accepted' : null };
export type ConversationType = { 'group' : null } |
  { 'direct' : null };
export interface CreateGroupRequest {
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
}
export interface DirectConversationSummary {
  'otherUsername' : string,
  'otherUserId' : UserId,
  'lastMessage' : [] | [Message],
  'conversationId' : bigint,
  'unreadCount' : bigint,
}
export interface EditGroupRequest {
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : GroupId,
  'ownerId' : UserId,
  'icon' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export type GroupId = bigint;
export interface GroupMember {
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : GroupMemberRole,
  'groupId' : GroupId,
}
export type GroupMemberRole = { 'member' : null } |
  { 'owner' : null };
export interface GroupSummary {
  'memberCount' : bigint,
  'lastMessage' : [] | [MessageId],
  'group' : Group,
  'unreadCount' : bigint,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'file' : [] | [ExternalBlob],
  'kind' : MessageKind,
  'createdAt' : Timestamp,
  'senderId' : UserId,
}
export type MessageId = bigint;
export type MessageKind = { 'file' : null } |
  { 'text' : null };
export type PresenceStatus = { 'away' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface ProfilePublic {
  'status' : string,
  'username' : string,
  'userId' : UserId,
  'presence' : PresenceStatus,
  'lastSeen' : Timestamp,
  'avatar' : [] | [ExternalBlob],
}
export interface ReactionEntry { 'emoji' : string, 'users' : Array<UserId> }
export interface SaveProfileRequest {
  'status' : string,
  'username' : string,
  'avatar' : [] | [ExternalBlob],
}
export interface SearchResult {
  'content' : string,
  'messageId' : bigint,
  'createdAt' : Timestamp,
  'conversationId' : string,
  'senderId' : UserId,
  'conversationType' : ConversationType,
}
export interface SendMessageRequest {
  'content' : string,
  'file' : [] | [ExternalBlob],
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptCall' : ActorMethod<[CallId, string], undefined>,
  'acceptContactRequest' : ActorMethod<[bigint], undefined>,
  'addGroupMember' : ActorMethod<[GroupId, UserId], undefined>,
  'addIceCandidate' : ActorMethod<[CallId, string, boolean], undefined>,
  'addReaction' : ActorMethod<[string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCall' : ActorMethod<[UserId, string, boolean], CallId>,
  'createGroup' : ActorMethod<[CreateGroupRequest], GroupId>,
  'declineCall' : ActorMethod<[CallId], undefined>,
  'editGroup' : ActorMethod<[GroupId, EditGroupRequest], undefined>,
  'findUserByUsername' : ActorMethod<[string], [] | [ProfilePublic]>,
  'getCallState' : ActorMethod<[CallId], [] | [CallStatePublic]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getDirectConversationSummaries' : ActorMethod<
    [],
    Array<DirectConversationSummary>
  >,
  'getDirectMessageReaders' : ActorMethod<[bigint, MessageId], Array<UserId>>,
  'getDirectMessages' : ActorMethod<
    [bigint, [] | [MessageId], bigint],
    Array<Message>
  >,
  'getGroup' : ActorMethod<[GroupId], [] | [Group]>,
  'getGroupMembers' : ActorMethod<[GroupId], Array<GroupMember>>,
  'getGroupMessageReaders' : ActorMethod<[GroupId, MessageId], Array<UserId>>,
  'getGroupMessages' : ActorMethod<
    [GroupId, [] | [MessageId], bigint],
    Array<Message>
  >,
  'getOrCreateDirectConversation' : ActorMethod<[UserId], bigint>,
  'getPendingCall' : ActorMethod<[], [] | [CallStatePublic]>,
  'getPendingContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getReactions' : ActorMethod<[string, bigint], Array<ReactionEntry>>,
  'getSentContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getTypingUsers' : ActorMethod<[string], Array<UserId>>,
  'getUnreadDirectCount' : ActorMethod<[bigint], bigint>,
  'getUserGroups' : ActorMethod<[], Array<GroupSummary>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [ProfilePublic]>,
  'hangupCall' : ActorMethod<[CallId], undefined>,
  'heartbeat' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveGroup' : ActorMethod<[GroupId], undefined>,
  'markDirectRead' : ActorMethod<[bigint, MessageId], undefined>,
  'markGroupRead' : ActorMethod<[GroupId, MessageId], undefined>,
  'rejectContactRequest' : ActorMethod<[bigint], undefined>,
  'removeContact' : ActorMethod<[UserId], undefined>,
  'removeGroupMember' : ActorMethod<[GroupId, UserId], undefined>,
  'removeReaction' : ActorMethod<[string, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileRequest], undefined>,
  'searchMessages' : ActorMethod<[string], Array<SearchResult>>,
  'sendContactRequest' : ActorMethod<[UserId], bigint>,
  'sendDirectMessage' : ActorMethod<[bigint, SendMessageRequest], MessageId>,
  'sendGroupMessage' : ActorMethod<[GroupId, SendMessageRequest], MessageId>,
  'setPresence' : ActorMethod<[PresenceStatus], undefined>,
  'setTypingStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];