/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchResult {
    content: string;
    messageId: bigint;
    createdAt: Timestamp;
    conversationId: string;
    senderId: UserId;
    conversationType: ConversationType;
}
export type Timestamp = bigint;
export interface SaveProfileRequest {
    status: string;
    username: string;
    avatar?: ExternalBlob;
}
export interface Group {
    id: GroupId;
    ownerId: UserId;
    icon?: ExternalBlob;
    name: string;
    createdAt: Timestamp;
    description: string;
}
export type GroupId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SendMessageRequest {
    content: string;
    file?: ExternalBlob;
}
export interface GroupSummary {
    memberCount: bigint;
    lastMessage?: MessageId;
    group: Group;
    unreadCount: bigint;
}
export interface ContactRequest {
    id: bigint;
    to: UserId;
    status: ContactStatus;
    from: UserId;
    createdAt: Timestamp;
}
export interface EditGroupRequest {
    icon?: ExternalBlob;
    name: string;
    description: string;
}
export interface GroupMember {
    userId: UserId;
    joinedAt: Timestamp;
    role: GroupMemberRole;
    groupId: GroupId;
}
export interface Contact {
    username: string;
    userId: UserId;
    addedAt: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CreateGroupRequest {
    icon?: ExternalBlob;
    name: string;
    description: string;
}
export interface CallStatePublic {
    id: CallId;
    status: CallStatus;
    callerCandidates: Array<string>;
    createdAt: Timestamp;
    sdpOffer?: string;
    calleeId: UserId;
    callerId: UserId;
    updatedAt: Timestamp;
    calleeCandidates: Array<string>;
    isVideo: boolean;
    sdpAnswer?: string;
}
export type UserId = Principal;
export interface ReactionEntry {
    emoji: string;
    users: Array<UserId>;
}
export type MessageId = bigint;
export interface DirectConversationSummary {
    otherUsername: string;
    otherUserId: UserId;
    lastMessage?: Message;
    conversationId: bigint;
    unreadCount: bigint;
}
export interface Message {
    id: MessageId;
    content: string;
    file?: ExternalBlob;
    kind: MessageKind;
    createdAt: Timestamp;
    senderId: UserId;
}
export type CallId = bigint;
export interface ProfilePublic {
    status: string;
    username: string;
    userId: UserId;
    presence: PresenceStatus;
    lastSeen: Timestamp;
    avatar?: ExternalBlob;
}
export enum CallStatus {
    active = "active",
    ringing = "ringing",
    missed = "missed",
    ended = "ended",
    declined = "declined"
}
export enum ContactStatus {
    pending = "pending",
    blocked = "blocked",
    accepted = "accepted"
}
export enum ConversationType {
    group = "group",
    direct = "direct"
}
export enum GroupMemberRole {
    member = "member",
    owner = "owner"
}
export enum MessageKind {
    file = "file",
    text = "text"
}
export enum PresenceStatus {
    away = "away",
    offline = "offline",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptCall(callId: CallId, sdpAnswer: string): Promise<void>;
    acceptContactRequest(requestId: bigint): Promise<void>;
    addGroupMember(groupId: GroupId, newMember: UserId): Promise<void>;
    addIceCandidate(callId: CallId, candidate: string, isCallee: boolean): Promise<void>;
    addReaction(conversationId: string, messageId: bigint, emoji: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCall(calleeId: UserId, sdpOffer: string, isVideo: boolean): Promise<CallId>;
    createGroup(req: CreateGroupRequest): Promise<GroupId>;
    declineCall(callId: CallId): Promise<void>;
    editGroup(groupId: GroupId, req: EditGroupRequest): Promise<void>;
    findUserByUsername(username: string): Promise<ProfilePublic | null>;
    getCallState(callId: CallId): Promise<CallStatePublic | null>;
    getCallerUserProfile(): Promise<ProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContacts(): Promise<Array<Contact>>;
    getDirectConversationSummaries(): Promise<Array<DirectConversationSummary>>;
    getDirectMessageReaders(conversationId: bigint, messageId: MessageId): Promise<Array<UserId>>;
    getDirectMessages(conversationId: bigint, before: MessageId | null, limit: bigint): Promise<Array<Message>>;
    getGroup(groupId: GroupId): Promise<Group | null>;
    getGroupMembers(groupId: GroupId): Promise<Array<GroupMember>>;
    getGroupMessageReaders(groupId: GroupId, messageId: MessageId): Promise<Array<UserId>>;
    getGroupMessages(groupId: GroupId, before: MessageId | null, limit: bigint): Promise<Array<Message>>;
    getOrCreateDirectConversation(other: UserId): Promise<bigint>;
    getPendingCall(): Promise<CallStatePublic | null>;
    getPendingContactRequests(): Promise<Array<ContactRequest>>;
    getReactions(conversationId: string, messageId: bigint): Promise<Array<ReactionEntry>>;
    getSentContactRequests(): Promise<Array<ContactRequest>>;
    getTypingUsers(conversationId: string): Promise<Array<UserId>>;
    getUnreadDirectCount(conversationId: bigint): Promise<bigint>;
    getUserGroups(): Promise<Array<GroupSummary>>;
    getUserProfile(userId: UserId): Promise<ProfilePublic | null>;
    hangupCall(callId: CallId): Promise<void>;
    heartbeat(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    leaveGroup(groupId: GroupId): Promise<void>;
    markDirectRead(conversationId: bigint, upToMessageId: MessageId): Promise<void>;
    markGroupRead(groupId: GroupId, upToMsgId: MessageId): Promise<void>;
    rejectContactRequest(requestId: bigint): Promise<void>;
    removeContact(target: UserId): Promise<void>;
    removeGroupMember(groupId: GroupId, target: UserId): Promise<void>;
    removeReaction(conversationId: string, messageId: bigint, emoji: string): Promise<void>;
    saveCallerUserProfile(req: SaveProfileRequest): Promise<void>;
    searchMessages(searchTerm: string): Promise<Array<SearchResult>>;
    sendContactRequest(target: UserId): Promise<bigint>;
    sendDirectMessage(conversationId: bigint, req: SendMessageRequest): Promise<MessageId>;
    sendGroupMessage(groupId: GroupId, req: SendMessageRequest): Promise<MessageId>;
    setPresence(presence: PresenceStatus): Promise<void>;
    setTypingStatus(conversationId: string, isTyping: boolean): Promise<void>;
}
import type { CallId as _CallId, CallStatePublic as _CallStatePublic, CallStatus as _CallStatus, ContactRequest as _ContactRequest, ContactStatus as _ContactStatus, ConversationType as _ConversationType, CreateGroupRequest as _CreateGroupRequest, DirectConversationSummary as _DirectConversationSummary, EditGroupRequest as _EditGroupRequest, ExternalBlob as _ExternalBlob, Group as _Group, GroupId as _GroupId, GroupMember as _GroupMember, GroupMemberRole as _GroupMemberRole, GroupSummary as _GroupSummary, Message as _Message, MessageId as _MessageId, MessageKind as _MessageKind, PresenceStatus as _PresenceStatus, ProfilePublic as _ProfilePublic, SaveProfileRequest as _SaveProfileRequest, SearchResult as _SearchResult, SendMessageRequest as _SendMessageRequest, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptCall(arg0: CallId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptCall(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptCall(arg0, arg1);
            return result;
        }
    }
    async acceptContactRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptContactRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptContactRequest(arg0);
            return result;
        }
    }
    async addGroupMember(arg0: GroupId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async addIceCandidate(arg0: CallId, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIceCandidate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIceCandidate(arg0, arg1, arg2);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCall(arg0: UserId, arg1: string, arg2: boolean): Promise<CallId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCall(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCall(arg0, arg1, arg2);
            return result;
        }
    }
    async createGroup(arg0: CreateGroupRequest): Promise<GroupId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(await to_candid_CreateGroupRequest_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(await to_candid_CreateGroupRequest_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async declineCall(arg0: CallId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineCall(arg0);
            return result;
        }
    }
    async editGroup(arg0: GroupId, arg1: EditGroupRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editGroup(arg0, await to_candid_EditGroupRequest_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editGroup(arg0, await to_candid_EditGroupRequest_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async findUserByUsername(arg0: string): Promise<ProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findUserByUsername(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUserByUsername(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallState(arg0: CallId): Promise<CallStatePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallState(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallState(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<ProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getDirectConversationSummaries(): Promise<Array<DirectConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectConversationSummaries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectConversationSummaries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDirectMessageReaders(arg0: bigint, arg1: MessageId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessageReaders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessageReaders(arg0, arg1);
            return result;
        }
    }
    async getDirectMessages(arg0: bigint, arg1: MessageId | null, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessages(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessages(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroup(arg0: GroupId): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMembers(arg0: GroupId): Promise<Array<GroupMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMessageReaders(arg0: GroupId, arg1: MessageId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessageReaders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessageReaders(arg0, arg1);
            return result;
        }
    }
    async getGroupMessages(arg0: GroupId, arg1: MessageId | null, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateDirectConversation(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateDirectConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateDirectConversation(arg0);
            return result;
        }
    }
    async getPendingCall(): Promise<CallStatePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCall();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCall();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingContactRequests();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingContactRequests();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: string, arg1: bigint): Promise<Array<ReactionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0, arg1);
            return result;
        }
    }
    async getSentContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentContactRequests();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentContactRequests();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTypingUsers(arg0: string): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingUsers(arg0);
            return result;
        }
    }
    async getUnreadDirectCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadDirectCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadDirectCount(arg0);
            return result;
        }
    }
    async getUserGroups(): Promise<Array<GroupSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGroups();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGroups();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<ProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async hangupCall(arg0: CallId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.hangupCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hangupCall(arg0);
            return result;
        }
    }
    async heartbeat(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeat();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async leaveGroup(arg0: GroupId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async markDirectRead(arg0: bigint, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDirectRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDirectRead(arg0, arg1);
            return result;
        }
    }
    async markGroupRead(arg0: GroupId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markGroupRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGroupRead(arg0, arg1);
            return result;
        }
    }
    async rejectContactRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectContactRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectContactRequest(arg0);
            return result;
        }
    }
    async removeContact(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return result;
        }
    }
    async removeGroupMember(arg0: GroupId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGroupMember(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileRequest_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileRequest_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchMessages(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMessages(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMessages(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendContactRequest(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendContactRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendContactRequest(arg0);
            return result;
        }
    }
    async sendDirectMessage(arg0: bigint, arg1: SendMessageRequest): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, await to_candid_SendMessageRequest_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, await to_candid_SendMessageRequest_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async sendGroupMessage(arg0: GroupId, arg1: SendMessageRequest): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessage(arg0, await to_candid_SendMessageRequest_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessage(arg0, await to_candid_SendMessageRequest_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setPresence(arg0: PresenceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPresence(to_candid_PresenceStatus_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPresence(to_candid_PresenceStatus_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTypingStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTypingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTypingStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CallStatePublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatePublic): CallStatePublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ContactRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactRequest): ContactRequest {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ContactStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactStatus): ContactStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ConversationType_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationType): ConversationType {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
async function from_candid_DirectConversationSummary_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DirectConversationSummary): Promise<DirectConversationSummary> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GroupMemberRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupMemberRole): GroupMemberRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_GroupMember_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupMember): GroupMember {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_GroupSummary_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupSummary): Promise<GroupSummary> {
    return await from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_Group_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Group): Promise<Group> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MessageKind_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageKind): MessageKind {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Message_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PresenceStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PresenceStatus): PresenceStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ProfilePublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfilePublic): Promise<ProfilePublic> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResult_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResult): SearchResult {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfilePublic]): Promise<ProfilePublic | null> {
    return value.length === 0 ? null : await from_candid_ProfilePublic_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallStatePublic]): CallStatePublic | null {
    return value.length === 0 ? null : from_candid_CallStatePublic_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Promise<Message | null> {
    return value.length === 0 ? null : await from_candid_Message_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Promise<Group | null> {
    return value.length === 0 ? null : await from_candid_Group_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    username: string;
    userId: _UserId;
    presence: _PresenceStatus;
    lastSeen: _Timestamp;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    status: string;
    username: string;
    userId: UserId;
    presence: PresenceStatus;
    lastSeen: Timestamp;
    avatar?: ExternalBlob;
}> {
    return {
        status: value.status,
        username: value.username,
        userId: value.userId,
        presence: from_candid_PresenceStatus_n17(_uploadFile, _downloadFile, value.presence),
        lastSeen: value.lastSeen,
        avatar: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CallId;
    status: _CallStatus;
    callerCandidates: Array<string>;
    createdAt: _Timestamp;
    sdpOffer: [] | [string];
    calleeId: _UserId;
    callerId: _UserId;
    updatedAt: _Timestamp;
    calleeCandidates: Array<string>;
    isVideo: boolean;
    sdpAnswer: [] | [string];
}): {
    id: CallId;
    status: CallStatus;
    callerCandidates: Array<string>;
    createdAt: Timestamp;
    sdpOffer?: string;
    calleeId: UserId;
    callerId: UserId;
    updatedAt: Timestamp;
    calleeCandidates: Array<string>;
    isVideo: boolean;
    sdpAnswer?: string;
} {
    return {
        id: value.id,
        status: from_candid_CallStatus_n24(_uploadFile, _downloadFile, value.status),
        callerCandidates: value.callerCandidates,
        createdAt: value.createdAt,
        sdpOffer: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.sdpOffer)),
        calleeId: value.calleeId,
        callerId: value.callerId,
        updatedAt: value.updatedAt,
        calleeCandidates: value.calleeCandidates,
        isVideo: value.isVideo,
        sdpAnswer: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.sdpAnswer))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    otherUsername: string;
    otherUserId: _UserId;
    lastMessage: [] | [_Message];
    conversationId: bigint;
    unreadCount: bigint;
}): Promise<{
    otherUsername: string;
    otherUserId: UserId;
    lastMessage?: Message;
    conversationId: bigint;
    unreadCount: bigint;
}> {
    return {
        otherUsername: value.otherUsername,
        otherUserId: value.otherUserId,
        lastMessage: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.lastMessage)),
        conversationId: value.conversationId,
        unreadCount: value.unreadCount
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    file: [] | [_ExternalBlob];
    kind: _MessageKind;
    createdAt: _Timestamp;
    senderId: _UserId;
}): Promise<{
    id: MessageId;
    content: string;
    file?: ExternalBlob;
    kind: MessageKind;
    createdAt: Timestamp;
    senderId: UserId;
}> {
    return {
        id: value.id,
        content: value.content,
        file: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.file)),
        kind: from_candid_MessageKind_n35(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        senderId: value.senderId
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GroupId;
    ownerId: _UserId;
    icon: [] | [_ExternalBlob];
    name: string;
    createdAt: _Timestamp;
    description: string;
}): Promise<{
    id: GroupId;
    ownerId: UserId;
    icon?: ExternalBlob;
    name: string;
    createdAt: Timestamp;
    description: string;
}> {
    return {
        id: value.id,
        ownerId: value.ownerId,
        icon: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.icon)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    joinedAt: _Timestamp;
    role: _GroupMemberRole;
    groupId: _GroupId;
}): {
    userId: UserId;
    joinedAt: Timestamp;
    role: GroupMemberRole;
    groupId: GroupId;
} {
    return {
        userId: value.userId,
        joinedAt: value.joinedAt,
        role: from_candid_GroupMemberRole_n45(_uploadFile, _downloadFile, value.role),
        groupId: value.groupId
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: _UserId;
    status: _ContactStatus;
    from: _UserId;
    createdAt: _Timestamp;
}): {
    id: bigint;
    to: UserId;
    status: ContactStatus;
    from: UserId;
    createdAt: Timestamp;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_ContactStatus_n50(_uploadFile, _downloadFile, value.status),
        from: value.from,
        createdAt: value.createdAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberCount: bigint;
    lastMessage: [] | [_MessageId];
    group: _Group;
    unreadCount: bigint;
}): Promise<{
    memberCount: bigint;
    lastMessage?: MessageId;
    group: Group;
    unreadCount: bigint;
}> {
    return {
        memberCount: value.memberCount,
        lastMessage: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.lastMessage)),
        group: await from_candid_Group_n40(_uploadFile, _downloadFile, value.group),
        unreadCount: value.unreadCount
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    messageId: bigint;
    createdAt: _Timestamp;
    conversationId: string;
    senderId: _UserId;
    conversationType: _ConversationType;
}): {
    content: string;
    messageId: bigint;
    createdAt: Timestamp;
    conversationId: string;
    senderId: UserId;
    conversationType: ConversationType;
} {
    return {
        content: value.content,
        messageId: value.messageId,
        createdAt: value.createdAt,
        conversationId: value.conversationId,
        senderId: value.senderId,
        conversationType: from_candid_ConversationType_n61(_uploadFile, _downloadFile, value.conversationType)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    away: null;
} | {
    offline: null;
} | {
    online: null;
}): PresenceStatus {
    return "away" in value ? PresenceStatus.away : "offline" in value ? PresenceStatus.offline : "online" in value ? PresenceStatus.online : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    ringing: null;
} | {
    missed: null;
} | {
    ended: null;
} | {
    declined: null;
}): CallStatus {
    return "active" in value ? CallStatus.active : "ringing" in value ? CallStatus.ringing : "missed" in value ? CallStatus.missed : "ended" in value ? CallStatus.ended : "declined" in value ? CallStatus.declined : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: null;
} | {
    text: null;
}): MessageKind {
    return "file" in value ? MessageKind.file : "text" in value ? MessageKind.text : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    owner: null;
}): GroupMemberRole {
    return "member" in value ? GroupMemberRole.member : "owner" in value ? GroupMemberRole.owner : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    blocked: null;
} | {
    accepted: null;
}): ContactStatus {
    return "pending" in value ? ContactStatus.pending : "blocked" in value ? ContactStatus.blocked : "accepted" in value ? ContactStatus.accepted : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    group: null;
} | {
    direct: null;
}): ConversationType {
    return "group" in value ? ConversationType.group : "direct" in value ? ConversationType.direct : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DirectConversationSummary>): Promise<Array<DirectConversationSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DirectConversationSummary_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupMember>): Array<GroupMember> {
    return value.map((x)=>from_candid_GroupMember_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactRequest>): Array<ContactRequest> {
    return value.map((x)=>from_candid_ContactRequest_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupSummary>): Promise<Array<GroupSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GroupSummary_n53(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SearchResult>): Array<SearchResult> {
    return value.map((x)=>from_candid_SearchResult_n59(_uploadFile, _downloadFile, x));
}
async function to_candid_CreateGroupRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGroupRequest): Promise<_CreateGroupRequest> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_EditGroupRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditGroupRequest): Promise<_EditGroupRequest> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PresenceStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PresenceStatus): _PresenceStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_SaveProfileRequest_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileRequest): Promise<_SaveProfileRequest> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function to_candid_SendMessageRequest_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SendMessageRequest): Promise<_SendMessageRequest> {
    return await to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageId | null): [] | [_MessageId] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    icon?: ExternalBlob;
    name: string;
    description: string;
}): Promise<{
    icon: [] | [_ExternalBlob];
    name: string;
    description: string;
}> {
    return {
        icon: value.icon ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.icon)) : candid_none(),
        name: value.name,
        description: value.description
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    username: string;
    avatar?: ExternalBlob;
}): Promise<{
    status: string;
    username: string;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        status: value.status,
        username: value.username,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
async function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    file?: ExternalBlob;
}): Promise<{
    content: string;
    file: [] | [_ExternalBlob];
}> {
    return {
        content: value.content,
        file: value.file ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.file)) : candid_none()
    };
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PresenceStatus): {
    away: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == PresenceStatus.away ? {
        away: null
    } : value == PresenceStatus.offline ? {
        offline: null
    } : value == PresenceStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
